/*
 * DO NOT MODIFY.
 *
 * This file was generated by arch/um/Makefile
 *
 */

#define HOST_SC_TRAPNO 48 /* offsetof(struct sigcontext, trapno)	# */
#define HOST_SC_ERR 52 /* offsetof(struct sigcontext, err)	# */
#define HOST_SC_CR2 84 /* offsetof(struct sigcontext, cr2)	# */
#define HOST_FP_SIZE 27 /* sizeof(struct user_fpregs_struct)	# */
#define HOST_FPX_SIZE 128 /* sizeof(struct user_fpxregs_struct)	# */
#define HOST_IP 12 /* EIP	# */
#define HOST_SP 15 /* UESP	# */
#define HOST_EFLAGS 14 /* EFL	# */
#define HOST_EAX 6 /* EAX	# */
#define HOST_EBX 0 /* EBX	# */
#define HOST_ECX 1 /* ECX	# */
#define HOST_EDX 2 /* EDX	# */
#define HOST_ESI 3 /* ESI	# */
#define HOST_EDI 4 /* EDI	# */
#define HOST_EBP 5 /* EBP	# */
#define HOST_CS 13 /* CS	# */
#define HOST_SS 16 /* SS	# */
#define HOST_DS 7 /* DS	# */
#define HOST_FS 9 /* FS	# */
#define HOST_ES 8 /* ES	# */
#define HOST_GS 10 /* GS	# */
#define UM_FRAME_SIZE 68 /* sizeof(struct user_regs_struct)	# */
#define UM_POLLIN 1 /* POLLIN	# */
#define UM_POLLPRI 2 /* POLLPRI	# */
#define UM_POLLOUT 4 /* POLLOUT	# */
#define UM_PROT_READ 1 /* PROT_READ	# */
#define UM_PROT_WRITE 2 /* PROT_WRITE	# */
#define UM_PROT_EXEC 4 /* PROT_EXEC	# */

